#[test]
fn succeed() {
    assert_eq!(1, 1)
}

#[test]
fn panic() {
    assert_eq!(2, 1)
}
